apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-configmap
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       off
    [INPUT]
        Name         tail
        Tag          counter_log
        Path         /var/log/1.log
    [OUTPUT]
        Name          forward
        Match         *
        Host          202.30.164.204
        Port          24224
